version: '3.9'
services:
  flask_1:
    build:
      context: flask_app
      dockerfile: Dockerfile
    volumes:
      - ./flask_app:/code:cached
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - ARCHITECTURE=resnet18
  flask_2:
    build:
      context: flask_app
      dockerfile: Dockerfile
    volumes:
      - ./flask_app:/code:cached
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - ARCHITECTURE=resnet34

  aiohttp_app:
    build:
      context: aiohttp_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"